### ISSUE TITLE
upgrade master to Java 8

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#144]
In order to leverage all the configuration options described in https://jenkins.io/blog/2016/11/21/gc-tuning/

This would certainly help with the repeated crashed of the master.

**Comment by nuclearsandwich** [comment]
Resolved now that Xenial is the default.

There is a GC tuning discussion specific to build.ros.org in the production configuration repository.

**Comment by dirk-thomas** [comment]
Is the task for actually using Java 8 specific options like the GC tuning ticketed anywhere? If not I would suggest to keep this one open until that has been done.

**Comment by nuclearsandwich** [comment]
> Is the task for actually using Java 8 specific options like the GC tuning ticketed anywhere?

I literally referenced that issue in my comment closing the issue. Here is a direct link that will be inaccessible to folks outside OSRF https://github.com/osrf/buildfarm_deployment_config/issues/16

**Comment by dirk-thomas** [comment]
> I literally referenced that issue in my comment closing the issue.

Your previous comment only mentions a "tuning discussion" so it was not obvious that there is a ticket tracking this.

Thanks for adding the link to the ticket (even when it is not public). I am sure it will help future readers to find the follow up work.

**Comment by nuclearsandwich** [comment]
> Your previous comment only mentions a "tuning discussion" so it was not obvious that there is a ticket tracking this.

Apologies for the 'tude. I'm definitely reaching the end of a long week. In the past I've tried to avoid links in public-facing projects to private ones as it hurts readability for the majority of participants. But I should get better about either back-referencing the public issue from the private one so that individuals with access will see it or posting links but clarifying their visibility so participants without access will know that the link is inaccessible rather than removed.
