### ISSUE TITLE
reconfigure is blocked by connecting to ip.

### ISSUE THREAD

**Issue by SquirrelCZE** [ros-infrastructure/buildfarm_deployment#161]
Hi folks,

I am trunning to setup buildfarm master on custom virtualizer at my university.
I found out that ./reconfigure.bash from config repository is taking too long, and tried to figure out what is happening.

U used strace and it seems that problem is this part:

`
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 6
fstat(6, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
connect(6, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("169.254.169.254")}, 16) = -1 ETIMEDOUT (Connection timed out)
close(6)  
`

From what I am able to find out, it seems that this IP is used by cloud providers for providing metainformation. ( https://serverfault.com/questions/427018/what-is-this-ip-address-169-254-169-254 )

I simply avoided this problem by blocking any outgoing connection to that API and it seems everything is fine...

**Comment by tfoote** [comment]
Can you clarify what process was trying to connect to that address? And do you have the console outputs? It sounds like your networking might not have been fully setup? That's the default link local address scheme for when a DHCP lease is not found.

**Comment by SquirrelCZE** [comment]
I see.

I installed ubuntu 14.04 on centos hypervizor. 
Git cloned my custom buildfarm_deployment_config (just filled appropiate settings) and executed ./reconfigure.bash master  (same happend on repo)

I debugged it with:
`
strace puppet apply --verbose -v /root/buildfarm_deployment/master/manifests/site.pp --modulepath=/root/buildfarm_deployment/master/:/root/buildfarm_deployment/master/modules
` 

afaik network is OK and I do not have any problems. Maybe I should provide longer strace output?

**Comment by nuclearsandwich** [comment]
@SquirrelCZE Right around the time you opened this issue we completed a refactor of the buildfarm deployment which targets Ubuntu xenial rather than trusty. We aren't able to provide much support for the trusty branch going forward, but it will be available for use as https://github.com/ros-infrastructure/buildfarm_deployment/tree/trusty

If you're still unable to get the deployment working, you might have better luck deploying on xenial. I'm going to close this issue but feel free to respond, open new issues, or post questions on https://answers.ros.org if you have them.
